version: '3'
services:
  my_ubuntu:
    image: phatnguyenuit/my-ubuntu
    container_name: my_ubuntu_environment
    depends_on:
      - db
    links:
      - db
    volumes:
      - ./sources:/home/dev/sources

  db:
    image: postgres:9.5
    container_name: my_db
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
  pgadmin:
    image: dpage/pgadmin4
    container_name: my_admin
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev@example.com
      - POSTGRES_USER=dev
      - PGADMIN_LISTEN_PORT=9000
    depends_on:
      - db
    links:
      - db
    ports:
      - 9000:9000

networks:
  db:
