version: '3'
services:
  my_ubuntu:
    build: ./docker/my_ubuntu
    image: phatnguyenuit/my_ubuntu
    container_name: my_ubuntu_environment
    volumes:
      - ./sources:/home/dev/sources
    restart: 'no'
    network_mode: 'bridge'
networks:
  default:
    external:
      name: bridge
